// Load list of artists
export const LOAD_ARTISTS = "LOAD_ARTISTS";
export const LOAD_ARTISTS_SUCCESS = "LOAD_ARTISTS_SUCCESS";
// Load playlists
export const LOAD_PLAYLISTS = "LOAD_PLAYLISTS";
export const LOAD_PLAYLISTS_SUCCESS = "LOAD_PLAYLISTS_SUCCESS";
// Load single playlist
export const LOAD_ONE_PLAYLIST = "LOAD_ONE_PLAYLIST";
export const LOAD_ONE_PLAYLIST_SUCCESS = "LOAD_ONE_PLAYLIST_SUCCESS";
// Edit playlist
export const ADD_SONGS_TO_PLAYLIST = "ADD_SONGS_TO_PLAYLIST";
export const ADD_SONGS_TO_PLAYLIST_RESULT = "ADD_SONGS_TO_PLAYLIST_RESULT";
// Songs management
export const ADD_SONGS_TO_QUEUE = "ADD_SONGS_TO_QUEUE"
export const PLAY_NEXT_SONG = "PLAY_NEXT_SONG"
export const PLAY_PREVIOUS_SONG = "PLAY_PREVIOUS_SONG"
