// Load list of artists
export const LOAD_ARTISTS = "LOAD_ARTISTS";
export const LOAD_ARTISTS_SUCCESS = "LOAD_ARTISTS_SUCCESS";
// Load playlists
export const LOAD_PLAYLISTS = "LOAD_PLAYLISTS";
export const LOAD_PLAYLISTS_SUCCESS = "LOAD_PLAYLISTS_SUCCESS";
// Edit playlist
export const ADD_SONGS_TO_PLAYLIST_RESULT = "ADD_SONGS_TO_PLAYLIST_RESULT";
export const REMOVE_SONGS_FROM_PLAYLIST_RESULT = "REMOVE_SONGS_FROM_PLAYLIST_RESULT";
export const DELETE_PLAYLIST_RESULT = "DELETE_PLAYLIST_RESULT"
// Songs management
export const ADD_SONGS_TO_QUEUE = "ADD_SONGS_TO_QUEUE"
export const PLAY_NEXT_SONG = "PLAY_NEXT_SONG"
export const PLAY_PREVIOUS_SONG = "PLAY_PREVIOUS_SONG"
