// Load list of artists
export const LOAD_ARTISTS = "LOAD_ARTISTS";
export const LOAD_ARTISTS_SUCCESS = "LOAD_ARTISTS_SUCCESS";
// Load playlists
export const LOAD_PLAYLISTS = "LOAD_PLAYLISTS";
export const LOAD_PLAYLISTS_SUCCESS = "LOAD_PLAYLISTS_SUCCESS";
export const LOAD_SINGLE_PLAYLIST_REQUEST = "LOAD_SINGLE_PLAYLIST_REQUEST"
export const LOAD_SINGLE_PLAYLIST_SUCCESS = "LOAD_SINGLE_PLAYLIST_SUCCESS"
// Edit playlist
export const ADD_SONGS_TO_PLAYLIST_RESULT = "ADD_SONGS_TO_PLAYLIST_RESULT";
export const REMOVE_SONGS_FROM_PLAYLIST_RESULT = "REMOVE_SONGS_FROM_PLAYLIST_RESULT";
export const DELETE_PLAYLIST_RESULT = "DELETE_PLAYLIST_RESULT"
export const EDIT_PLAYLIST_RESULT = "EDIT_PLAYLIST_RESULT"
// Songs management
export const ADD_SONGS_TO_QUEUE = "ADD_SONGS_TO_QUEUE"
export const PLAY_NEXT_SONG = "PLAY_NEXT_SONG"
export const PLAY_PREVIOUS_SONG = "PLAY_PREVIOUS_SONG"
export const STAR_SONG_RESULT = "STAR_SONG_RESULT"
// Authentication
export const LAZY_LOGIN_IGNORE = "LAZY_LOGIN_IGNORE"
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGOUT_USER = "LOGOUT_USER"
// API calls
export const BEGIN_ASYNC_OPERATION = "BEGIN_ASYNC_OPERATION"
export const END_ASYNC_OPERATION = "END_ASYNC_OPERATION"
// Search
export const SEARCH_RESULT = "SEARCH_RESULT"